AUTHOR := hmartzol
NAME := libftprintf.a
SRCDIR := src
INCDIRS := inc
MAIN := main.c
CFLAGS := -Wall -Wextra -Werror -g
PINC := ../libft/inc
CLIB := ../libft
LIB := ../libft/libft.a
include ../Makefiles/Makefile.gen
