AUTHOR := hmartzol
NAME := libftprintf.a
SRCDIR := src
INCDIRS := inc ../libft/inc
MAIN := main.c
CFLAGS := -Wall -Wextra -Werror -g
CLIB := ../libft
LIB := ../libft/libft.a
include ../Makefiles/Makefile.gen
