AUTHOR := hmartzol
NAME := libftthread.a
EXEARGS :=

MAIN := main.c

SRCDIR := src
INCDIRS := inc
OBJDIR := .obj
DEPDIR := .dep

CFLAGS := -Wall -Wextra -Werror -O2 -g
PINC := ../libft/inc
CLIB := ../libft
LIB := ../libft/libft.a
LARGS := -pthread

include ../Makefiles/Makefile.gen
